### ISSUE TITLE
No matching handler found

### ISSUE THREAD

**Issue by oderwat** [prasmussen/chrome-cli#19]
Well I may be just missing something obvious but I can't do anything because all I ever get is "No matching handler found".

**Comment by ZUCheema** [comment]
I'm facing the same issue when executing the command other than -h from Swift.

**Comment by gj-honey** [comment]
@prasmussen sorry to unearth this old issue, but would it be possible to just default to printing help when "no matching handler found" ? (and/or a slightly more useful message that invites the user to run `--help`?

(and as a side-note, having auto-completion for chrome-cli (#17)  would be a nice bonus/helper too)
