### ISSUE TITLE
Chromium CLI

### ISSUE THREAD

**Issue by dardo82** [prasmussen/chrome-cli#31]
I'm trying to build chrome-cli on Mac OSX 10.8.5 as i would to make a version for Chromium as there is one for Chrome Canary but i'm getting some errors.
If i do `brew unpack chrome-cli; cd chrome-cli-1.5.0; xcodebuild` i get errors about `no visible interface for SBElementArray` that `declares the selector firstObject`.

**Comment by prasmussen** [comment]
I can't help you with the build error, but to control chromium you need to replace `com.google.Chrome` with `org.chromium.Chromium` in `App.m`. I've added a link to a prebuilt chromium-cli in the README.

**Comment by dardo82** [comment]
Good, it works! :-D That was quick, thanks... ^_^ How can we now update the homebrew formula? ;-)

**Comment by dardo82** [comment]
OK, OS X 10.9 SDK is needed to build this and i was missing it, restoring it from Time Machine fixed this.

**Comment by dardo82** [comment]
I have made a pull request for the updated homebrew formula here: https://github.com/Homebrew/homebrew/pull/42731

**Comment by dardo82** [comment]
I have made a pull request for the updated homebrew formula here: https://github.com/Homebrew/homebrew/pull/42731

**Comment by dardo82** [comment]
I have made another pull request as the the previous one had problems: https://github.com/Homebrew/homebrew/pull/42849

**Comment by prasmussen** [comment]
Thanks :)

**Comment by dardo82** [comment]
:+1:

**Comment by CanRau** [comment]
How about a way to define that in the main cli itself? so it could work with all derivatives like Brave having just aliases. Or is that not possible? 🤔

**Comment by haakonstorm** [comment]
+1 for way to define this via `arg flags` :-)

<img width="1238" alt="Screenshot of iTerm2 (17-10-2020, 22-15-59)" src="https://user-images.githubusercontent.com/193781/96352811-a30c6680-10c6-11eb-8e2e-be571bafc9ae.png">

**Comment by prasmussen** [comment]
The latest version lets you override the bundle identifier, check the readme for more details.
