### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by arita37** [prasmussen/chrome-cli#41]
Thanks for your tool.
Any project of compiling one version for windows ?

**Comment by rcreasi** [comment]
I would also love that but I assume it would be a big lift. It's written in Objective-C so I don't think the code is easily portable. That said, apparently [it is possible](https://stackoverflow.com/a/141197).

**Comment by prasmussen** [comment]
They way this tools communicates with Chrome is OSX specific (AppleScript / ScriptingBridge) and won't work on Windows unfortunately.
