### ISSUE TITLE
execute/source no longer works in chrome 68

### ISSUE THREAD

**Issue by kevinfrommelt** [prasmussen/chrome-cli#45]

**Comment by prasmussen** [comment]
Confirmed.
`- (id) executeJavascript:(NSString *)javascript;` is still defined in `chrome.h` but it does not seem to do anything.

**Comment by simoheinonen** [comment]
Can confirm too

**Comment by simoheinonen** [comment]
Not sure if https://github.com/prasmussen/chrome-cli/commit/2a018277a1f113ec4d0aabf957d940ad7e505f5c was supposed to fix this but it didn't help 😢

**Comment by maxxiweb** [comment]
Same issue here!

**Comment by paulp** [comment]
Could there be a case issue? Poking around chromium source I only see `executeJavaScript` (inner capital S), not `executeJavascript`.

**Comment by prasmussen** [comment]
@paulp It was worth a try but it did not work:
```chrome-cli[89554:68984200] -[GoogleChromeTab executeJavaScript:]: unrecognized selector sent to instance 0x7fdbabd275c0```

**Comment by paulp** [comment]
[Is it this?](https://bugs.chromium.org/p/chromium/issues/detail?id=543437)

**Comment by kevinfrommelt** [comment]
I got this working again by enabling "Allow JavaScript from Apple Events" in Chrome

View > Developer > Allow JavaScript from Apple Events

**Comment by paulp** [comment]
@kevinfrommelt THANK YOU!

**Comment by paulp** [comment]
[Here's some additional context.](https://www.chromium.org/developers/applescript)

**Comment by maxxiweb** [comment]
@kevinfrommelt You're the boss!!

**Comment by prasmussen** [comment]
@kevinfrommelt and @paulp nice find! I've added a note about this in the readme.

**Comment by dentarg** [comment]
@prasmussen it is also needed for `chrome-cli source -t <id>` to work ([the note](https://github.com/prasmussen/chrome-cli/commit/f2f3615971cc2cec28aa28dae022c7b517bda047) in the readme didn't cover that)
