### ISSUE TITLE
`source` command no longer working

### ISSUE THREAD

**Issue by lthurston** [prasmussen/chrome-cli#48]
I haven't updated chrome-cli since this last worked just fine, so perhaps it's a change in Chrome itself.

I'm running Version 69.0.3497.81 (Official Build) (64-bit) on High Sierra.

Here's what I get:

```
$ chrome-cli list tabs
[990718318] Untitled spreadsheet - Google Sheets
[990718323] Issues · prasmussen/chrome-cli
$ chrome-cli source
$ chrome-cli source -t 990718323
$
```

Just nothing. The last time this worked fine for me was the beginning of August and today is the first time I've used my script that relies on this since then.

**Comment by prasmussen** [comment]
It's a change in chrome. The following also applies to the view source command.
```To execute javascript you must first allow it under View > Developer > Allow JavaScript from Apple Events. More details here.```

**Comment by lthurston** [comment]
Awesome, thank you!
