### ISSUE TITLE
add ability to specify chromium browsers like brave

### ISSUE THREAD

**Issue by darrenjennings** [prasmussen/chrome-cli#57]
Would be nice to identify any chromium browser running such as [Brave](https://www.brave.com/)
re: https://github.com/prasmussen/chrome-cli/issues/31#issuecomment-592900874

**Comment by darrenjennings** [comment]
I was able to build a brave version successfully in App.m

```diff
-    chromeApplication *chrome = [SBApplication applicationWithBundleIdentifier:@"com.google.Chrome"];
+    chromeApplication *chrome = [SBApplication applicationWithBundleIdentifier:@"com.brave.Browser"];
```

**Comment by bradparks** [comment]
This fork builds for brave supposedly as well
https://github.com/gtrabanco/chrome-cli/commit/640b8832f6f589e99112154c1708889bb426f065

**Comment by prasmussen** [comment]
The latest version lets you override the bundle identifier, check the readme for more details.
If you install via homebrew it comes bundled with brave-cli and vivaldi-cli.
