### ISSUE TITLE
Feature request: single command that combines `list links` and `list tabs`

### ISSUE THREAD

**Issue by tadhg-ohiggins** [prasmussen/chrome-cli#72]
I use `chrome-cli` to get a list of open URLs and the titles of their tabs, but in order to get this I need to run it twice, once with 
`list links` and once with `list tabs`.

It would be useful to have something like `list linkstabs` that printed the identifiers, the URLs, and the titles.

**Comment by prasmussen** [comment]
`list tablinks` is available in v1.9.1.
Homebrew formula is updated.
