### ISSUE TITLE
Chrome 108.0.5359.98 for Mac OSX breaks chrome-cli

### ISSUE THREAD

**Issue by duttly** [prasmussen/chrome-cli#75]
Waiting for chrome to start...
2022-12-08 22:07:41.590 chrome-cli[13366:9013130] Scripting Bridge could not launch application id com.google.Chrome.

Seems to be working well on Version 107.0.5304.121

**Comment by prasmussen** [comment]
Works for me
```
$ chrome-cli chrome version
Waiting for chrome to start...
108.0.5359.98
```

**Comment by philc** [comment]
Works for me on 110.0.5481.177. I suggest this be closed.
