### ISSUE TITLE
source command shows no output

### ISSUE THREAD

**Issue by ahter** [prasmussen/chrome-cli#80]
All other commands work as expected except `source`. 

What could be the underlying reason for this? (so I can check my settings and setup etc?)

Thank you.

**Comment by qzcsfchh** [comment]
In my practice, `execute` command output noting as well, does it work for you?

**Comment by prasmussen** [comment]
`source` and `execute` works for me.
Make sure to follow these instructions: https://github.com/prasmussen/chrome-cli?tab=readme-ov-file#javascript-execution-and-viewing-source

**Comment by qzcsfchh** [comment]
> `source` and `execute` works for me. Make sure to follow these instructions: https://github.com/prasmussen/chrome-cli?tab=readme-ov-file#javascript-execution-and-viewing-source



Thanks for replying, I've tried to turn on `View > Developer > Allow JavaScript from Apple Events`, and now I got expected output for `source` command, but `execute` still display empty result:
![image](https://github.com/prasmussen/chrome-cli/assets/17892408/0eb45bc8-8ac6-456e-9000-5b9f3b6066d1)

don't know what went wrong.

**Comment by prasmussen** [comment]
That example in the readme is meant to be run on the hackernews site.
This example should work on any site: `'(() => { return "foo" })()'`

**Comment by qzcsfchh** [comment]
> That example in the readme is meant to be run on the hackernews site. This example should work on any site: `'(() => { return "foo" })()'`

My bad, problem solved o(￣▽￣)ｄ
